services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      # Пароль для админа Keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      # Пока embedded БД для простоты
      KC_DB: dev-file
    ports:
      # Открываем порт для доступа
      - "8090:8090"
    command:
      # Запускаем в development режиме
      - start-dev

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_MULTIPLE_DATABASES: UsersDb,StorageDb
    ports:
      - "5432:5432"
    networks:
      - shop-pg-network
    labels:
      - app=shop
      
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.1-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    
    restart: unless-stopped
    
    networks:
      - shop-network
    labels:
      - app=shop
    healthcheck:
      test: "rabbitmqctl status > /dev/null 2>&1;"
      interval: 5s
      timeout: 5s
      retries: 5

  storage-service:
    image: storage-service
    build:
      context: .
      dockerfile: StorageService/StorageService.Api/Dockerfile
    ports:
    - "8080:8080"
    pull_policy: build
    environment:
      CONNECTION_STRING: Host=postgres:5432;Username=postgres;Password=P@ssw0rd;Database=StorageDb
      RMQ_HOST: rabbitmq
      RMQ_PORT: 5672
      RMQ_USER: guest
      RMQ_PASSWORD: guest
      RMQ_PRODUCT_FROM_STORAGE_QUEUE: storage-product-messages-queue
      ASPNETCORE_ENVIRONMENT: "Staging"
      ASPNETCORE_URLS: http://+:8080

    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: 5s
      timeout: 5s
      retries: 5
    
    restart: unless-stopped
    
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - shop-network
      - shop-pg-network

networks:
  shop-network:
    name: shop-network
    labels:
      - app=shop
  shop-pg-network:
    name: shop-pg-network
    labels:
      - app=shop